# Generated by Django 6.0.4 on 2026-04-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_adresse_commande_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('carte', 'Carte bancaire'), ('paypal', 'PayPal'), ('virement', 'Virement bancaire')], default='carte', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.commande')),
            ],
        ),
    ]
