# Generated by Django 6.0.6 on 2026-06-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('resolue', 'Résolue'), ('rejetee', 'Rejetée')], default='En cours', max_length=20),
        ),
    ]
