# Generated by Django 6.0.6 on 2026-06-17 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_reclamation_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('resolue', 'Résolue'), ('rejetee', 'Rejetée')], default='en_cours', max_length=20),
        ),
    ]
