# Generated by Django 6.0.6 on 2026-06-18 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_reclamation_client_alter_reclamation_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('ferme', 'Fermé')], default='non_lu', max_length=20)),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('urgent', 'Urgent')], default='moyenne', max_length=20)),
                ('reponse', models.TextField(blank=True, null=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_support', to=settings.AUTH_USER_MODEL)),
                ('reponse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_support', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Support',
                'verbose_name_plural': 'Messages Support',
                'ordering': ['-date_creation'],
            },
        ),
    ]
