# Generated by Django 6.0.6 on 2026-06-18 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_supportmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(blank=True, max_length=50, null=True)),
                ('type_demande', models.CharField(choices=[('retour', 'Retour produit'), ('echange', 'Échange produit'), ('garantie', 'Garantie'), ('remboursement', 'Remboursement'), ('reparation', 'Réparation')], max_length=20)),
                ('motif', models.CharField(choices=[('defectueux', 'Produit defectueux'), ('ne_correspond_pas', 'Ne correspond pas à la description'), ('mauvais_taille', 'Mauvaise taille / couleur'), ('livraison_tardive', 'Livraison tardive'), ('produit_abime', 'Produit abîmé / endommagé'), ('autre', 'Autre motif')], default='autre', max_length=30)),
                ('description', models.TextField(help_text='Décrivez votre demande en détails')),
                ('quantite', models.IntegerField(default=1)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='sav/')),
                ('piece_jointe_2', models.FileField(blank=True, null=True, upload_to='sav/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('en_cours', 'En cours de traitement'), ('expediee', 'Expédiée'), ('terminee', 'Terminée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire du support', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('adresse_retour', models.TextField(blank=True, null=True)),
                ('numero_suivi', models.CharField(blank=True, max_length=100, null=True)),
                ('transporteur', models.CharField(blank=True, max_length=50, null=True)),
                ('montant_remboursement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remboursement_effectue', models.BooleanField(default=False)),
                ('date_remboursement', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_sav', to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_sav', to='store.commande')),
                ('produits', models.ManyToManyField(blank=True, related_name='demandes_sav', to='store.produit')),
            ],
            options={
                'verbose_name': 'Demande SAV',
                'verbose_name_plural': 'Demandes SAV',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('retour', 'Bon de retour'), ('echange', "Bon d'échange"), ('reparation', 'Bon de réparation'), ('remboursement', 'Avis de remboursement')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents_sav/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_envoye', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='store.demandesav')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
